### PR TITLE
Wrapper for k4abt_tracker_configuration_t

### PR DESCRIPTION
**Pull request by jonas-hurst**
A proper python wrapper for k4abt_tracker_configuration_t.
Closes https://github.com/ibaiGorordo/pyKinectAzure/issues/89

### CODE REVIEW

**Comment by jonas-hurst** [comment]
The way it is implemented is analogous to k4a.configuration.

**Comment by TrevMasterFlex** [comment]
Just up-voting this since I had to do the following monkey-patch for my own specific use-case:

def get_tracker_configuration(self, model_type):
    tracker_config = pykinect_azure.k4abt_tracker_default_configuration
    tracker_config.sensor_orientation = pykinect_azure.K4ABT_SENSOR_ORIENTATION_COUNTERCLOCKWISE90
    tracker_config.processing_mode = pykinect_azure.K4ABT_TRACKER_PROCESSING_MODE_GPU_CUDA
    return tracker_config

pykinect_azure.Tracker.get_tracker_configuration = get_tracker_configuration

p.s. appreciate the library - and learning a lot from it

**Comment by jonas-hurst** [comment]
closes https://github.com/ibaiGorordo/pyKinectAzure/issues/113

**Comment by ibaiGorordo** [comment]
@jonas-hurst sorry for the delay, and thanks for the changes!

**Pull request merged**
